### ISSUE TITLE
wouldn't this be called an API/toolkit and not a framework?

### ISSUE THREAD

**Issue by Hri7566** [multiplayerpiano/mpp-commands-v1#1]
from what i've seen, frameworks are usually entire platforms on their own, like .NET, and would most likely make use of Inversion of Control

so wouldn't this just be an API?

**Comment by Zel9278** [comment]
> from what i've seen, frameworks are usually entire platforms on their own, like .NET, and would most likely make use of Inversion of Control
> 
> so wouldn't this just be an API?

Sure, it may not be a framework, but I've been playing around with "mpp-client-xt" and putting it in the base folder, so I may have to put the credit for mpp-client-xt in that Client.js.

**Comment by BopItFreak** [comment]
mpp-client-xt is literally just the original client but with socks-proxy-agent and https-proxy-agent for proxy support and a couple extra functions.
